# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_inventory.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1269, 712)
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/resources/dbIcon.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.Spanish, QtCore.QLocale.Panama))
        MainWindow.setIconSize(QtCore.QSize(60, 60))
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtGui.QTabWidget.Rounded)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(25, 25))
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_balance = QtGui.QWidget()
        self.tab_balance.setObjectName(_fromUtf8("tab_balance"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_balance)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setContentsMargins(0, 0, -1, -1)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.groupBox = QtGui.QGroupBox(self.tab_balance)
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout.setContentsMargins(0, -1, -1, -1)
        self.formLayout.setVerticalSpacing(6)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.dateAnnual = QtGui.QDateEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateAnnual.sizePolicy().hasHeightForWidth())
        self.dateAnnual.setSizePolicy(sizePolicy)
        self.dateAnnual.setDateTime(QtCore.QDateTime(QtCore.QDate(2017, 1, 2), QtCore.QTime(0, 0, 0)))
        self.dateAnnual.setDate(QtCore.QDate(2017, 1, 2))
        self.dateAnnual.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2017, 1, 2), QtCore.QTime(0, 0, 0)))
        self.dateAnnual.setMinimumDate(QtCore.QDate(2017, 1, 2))
        self.dateAnnual.setObjectName(_fromUtf8("dateAnnual"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.dateAnnual)
        self.radioMonthly = QtGui.QRadioButton(self.groupBox)
        self.radioMonthly.setObjectName(_fromUtf8("radioMonthly"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.radioMonthly)
        self.dateMonthly = QtGui.QDateEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateMonthly.sizePolicy().hasHeightForWidth())
        self.dateMonthly.setSizePolicy(sizePolicy)
        self.dateMonthly.setDateTime(QtCore.QDateTime(QtCore.QDate(2017, 5, 1), QtCore.QTime(0, 0, 0)))
        self.dateMonthly.setDate(QtCore.QDate(2017, 5, 1))
        self.dateMonthly.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2017, 5, 1), QtCore.QTime(0, 0, 0)))
        self.dateMonthly.setMinimumDate(QtCore.QDate(2017, 5, 1))
        self.dateMonthly.setCurrentSection(QtGui.QDateTimeEdit.MonthSection)
        self.dateMonthly.setObjectName(_fromUtf8("dateMonthly"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.dateMonthly)
        self.radioAnnual = QtGui.QRadioButton(self.groupBox)
        self.radioAnnual.setObjectName(_fromUtf8("radioAnnual"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.radioAnnual)
        self.radioHistoric = QtGui.QRadioButton(self.groupBox)
        self.radioHistoric.setChecked(True)
        self.radioHistoric.setObjectName(_fromUtf8("radioHistoric"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.radioHistoric)
        self.radioDaily = QtGui.QRadioButton(self.groupBox)
        self.radioDaily.setObjectName(_fromUtf8("radioDaily"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.radioDaily)
        self.horizontalLayout.addLayout(self.formLayout)
        self.calBalance = QtGui.QCalendarWidget(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calBalance.sizePolicy().hasHeightForWidth())
        self.calBalance.setSizePolicy(sizePolicy)
        self.calBalance.setMinimumSize(QtCore.QSize(300, 0))
        self.calBalance.setMaximumSize(QtCore.QSize(16777215, 100))
        self.calBalance.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.calBalance.setSelectedDate(QtCore.QDate(2017, 3, 1))
        self.calBalance.setMinimumDate(QtCore.QDate(2017, 3, 1))
        self.calBalance.setMaximumDate(QtCore.QDate(2100, 12, 31))
        self.calBalance.setFirstDayOfWeek(QtCore.Qt.Monday)
        self.calBalance.setGridVisible(True)
        self.calBalance.setHorizontalHeaderFormat(QtGui.QCalendarWidget.NoHorizontalHeader)
        self.calBalance.setVerticalHeaderFormat(QtGui.QCalendarWidget.NoVerticalHeader)
        self.calBalance.setNavigationBarVisible(True)
        self.calBalance.setObjectName(_fromUtf8("calBalance"))
        self.horizontalLayout.addWidget(self.calBalance)
        self.verticalLayout_7.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.tab_balance)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.tblPurchasesBal = QtGui.QTableView(self.groupBox_2)
        self.tblPurchasesBal.setAlternatingRowColors(True)
        self.tblPurchasesBal.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tblPurchasesBal.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tblPurchasesBal.setSortingEnabled(True)
        self.tblPurchasesBal.setObjectName(_fromUtf8("tblPurchasesBal"))
        self.tblPurchasesBal.horizontalHeader().setStretchLastSection(True)
        self.tblPurchasesBal.verticalHeader().setVisible(False)
        self.gridLayout_2.addWidget(self.tblPurchasesBal, 0, 0, 1, 1)
        self.verticalLayout_7.addWidget(self.groupBox_2)
        self.horizontalLayout_7.addLayout(self.verticalLayout_7)
        self.tblBalance = QtGui.QTableWidget(self.tab_balance)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblBalance.sizePolicy().hasHeightForWidth())
        self.tblBalance.setSizePolicy(sizePolicy)
        self.tblBalance.setMinimumSize(QtCore.QSize(350, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tblBalance.setFont(font)
        self.tblBalance.setFrameShape(QtGui.QFrame.Box)
        self.tblBalance.setFrameShadow(QtGui.QFrame.Raised)
        self.tblBalance.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tblBalance.setTabKeyNavigation(False)
        self.tblBalance.setProperty("showDropIndicator", False)
        self.tblBalance.setDragDropOverwriteMode(False)
        self.tblBalance.setAlternatingRowColors(False)
        self.tblBalance.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.tblBalance.setTextElideMode(QtCore.Qt.ElideLeft)
        self.tblBalance.setShowGrid(True)
        self.tblBalance.setGridStyle(QtCore.Qt.SolidLine)
        self.tblBalance.setWordWrap(True)
        self.tblBalance.setCornerButtonEnabled(False)
        self.tblBalance.setRowCount(7)
        self.tblBalance.setColumnCount(3)
        self.tblBalance.setObjectName(_fromUtf8("tblBalance"))
        item = QtGui.QTableWidgetItem()
        self.tblBalance.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tblBalance.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tblBalance.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tblBalance.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tblBalance.setItem(1, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tblBalance.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tblBalance.setItem(2, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tblBalance.setItem(2, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tblBalance.setItem(3, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tblBalance.setItem(3, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tblBalance.setItem(3, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tblBalance.setItem(4, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tblBalance.setItem(4, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tblBalance.setItem(4, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tblBalance.setItem(5, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tblBalance.setItem(5, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tblBalance.setItem(5, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tblBalance.setItem(6, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tblBalance.setItem(6, 2, item)
        self.tblBalance.horizontalHeader().setVisible(False)
        self.tblBalance.verticalHeader().setVisible(False)
        self.horizontalLayout_7.addWidget(self.tblBalance)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_7)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/resources/calculator.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_balance, icon1, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.toolBar.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.toolBar.setMovable(True)
        self.toolBar.setIconSize(QtCore.QSize(30, 30))
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.setFloatable(False)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.LeftToolBarArea, self.toolBar)
        self.actionPurchase = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/resources/plus-icon-0.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPurchase.setIcon(icon2)
        self.actionPurchase.setObjectName(_fromUtf8("actionPurchase"))
        self.actionRefresh = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/resources/Oxygen-Icons.org-Oxygen-Actions-view-refresh.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRefresh.setIcon(icon3)
        self.actionRefresh.setObjectName(_fromUtf8("actionRefresh"))
        self.toolBar.addAction(self.actionRefresh)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionPurchase)
        self.toolBar.addSeparator()

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Libra v1.0.0", None))
        self.groupBox.setTitle(_translate("MainWindow", "Period", None))
        self.dateAnnual.setDisplayFormat(_translate("MainWindow", "yyyy", None))
        self.radioMonthly.setText(_translate("MainWindow", "Monthly", None))
        self.dateMonthly.setDisplayFormat(_translate("MainWindow", "MMM/yyyy", None))
        self.radioAnnual.setText(_translate("MainWindow", "Annual", None))
        self.radioHistoric.setText(_translate("MainWindow", "Historic", None))
        self.radioDaily.setText(_translate("MainWindow", "Daily", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Purchases", None))
        __sortingEnabled = self.tblBalance.isSortingEnabled()
        self.tblBalance.setSortingEnabled(False)
        item = self.tblBalance.item(0, 0)
        item.setText(_translate("MainWindow", "Sales (paid)", None))
        item = self.tblBalance.item(0, 2)
        item.setText(_translate("MainWindow", "0.00", None))
        item = self.tblBalance.item(1, 0)
        item.setText(_translate("MainWindow", "Sales (credit)", None))
        item = self.tblBalance.item(1, 2)
        item.setText(_translate("MainWindow", "0.00", None))
        item = self.tblBalance.item(2, 0)
        item.setText(_translate("MainWindow", "Total revenue", None))
        item = self.tblBalance.item(2, 2)
        item.setText(_translate("MainWindow", "0.00", None))
        item = self.tblBalance.item(3, 0)
        item.setText(_translate("MainWindow", "Costs", None))
        item = self.tblBalance.item(3, 1)
        item.setText(_translate("MainWindow", "0.00", None))
        item = self.tblBalance.item(4, 0)
        item.setText(_translate("MainWindow", "Taxes", None))
        item = self.tblBalance.item(4, 1)
        item.setText(_translate("MainWindow", "0.00", None))
        item = self.tblBalance.item(5, 0)
        item.setText(_translate("MainWindow", "Profit", None))
        item = self.tblBalance.item(5, 2)
        item.setText(_translate("MainWindow", "0.00", None))
        item = self.tblBalance.item(6, 0)
        item.setText(_translate("MainWindow", "Profit (margin)", None))
        item = self.tblBalance.item(6, 2)
        item.setText(_translate("MainWindow", "0.00", None))
        self.tblBalance.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_balance), _translate("MainWindow", "Balance", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.actionPurchase.setText(_translate("MainWindow", "Purchase", None))
        self.actionRefresh.setText(_translate("MainWindow", "Refresh", None))

import res_rc
