# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_inventory.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1269, 712)
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/resources/dbIcon.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.Spanish, QtCore.QLocale.Panama))
        MainWindow.setIconSize(QtCore.QSize(60, 60))
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtGui.QTabWidget.Rounded)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(25, 25))
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_balance = QtGui.QWidget()
        self.tab_balance.setObjectName(_fromUtf8("tab_balance"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_balance)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setContentsMargins(0, 0, -1, -1)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_7.addLayout(self.verticalLayout_7)
        self.tblBalance = QtGui.QTableWidget(self.tab_balance)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblBalance.sizePolicy().hasHeightForWidth())
        self.tblBalance.setSizePolicy(sizePolicy)
        self.tblBalance.setMinimumSize(QtCore.QSize(350, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tblBalance.setFont(font)
        self.tblBalance.setFrameShape(QtGui.QFrame.Box)
        self.tblBalance.setFrameShadow(QtGui.QFrame.Raised)
        self.tblBalance.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tblBalance.setTabKeyNavigation(False)
        self.tblBalance.setProperty("showDropIndicator", False)
        self.tblBalance.setDragDropOverwriteMode(False)
        self.tblBalance.setAlternatingRowColors(False)
        self.tblBalance.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.tblBalance.setTextElideMode(QtCore.Qt.ElideLeft)
        self.tblBalance.setShowGrid(True)
        self.tblBalance.setGridStyle(QtCore.Qt.SolidLine)
        self.tblBalance.setWordWrap(True)
        self.tblBalance.setCornerButtonEnabled(False)
        self.tblBalance.setRowCount(7)
        self.tblBalance.setColumnCount(3)
        self.tblBalance.setObjectName(_fromUtf8("tblBalance"))
        item = QtGui.QTableWidgetItem()
        self.tblBalance.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tblBalance.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tblBalance.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tblBalance.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tblBalance.setItem(1, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tblBalance.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tblBalance.setItem(2, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tblBalance.setItem(2, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tblBalance.setItem(3, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tblBalance.setItem(3, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tblBalance.setItem(3, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tblBalance.setItem(4, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tblBalance.setItem(4, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tblBalance.setItem(4, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tblBalance.setItem(5, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tblBalance.setItem(5, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tblBalance.setItem(5, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tblBalance.setItem(6, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tblBalance.setItem(6, 2, item)
        self.tblBalance.horizontalHeader().setVisible(False)
        self.tblBalance.verticalHeader().setVisible(False)
        self.horizontalLayout_7.addWidget(self.tblBalance)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_7)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/resources/calculator.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_balance, icon1, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Libra v1.0.0", None))
        __sortingEnabled = self.tblBalance.isSortingEnabled()
        self.tblBalance.setSortingEnabled(False)
        item = self.tblBalance.item(0, 0)
        item.setText(_translate("MainWindow", "Sales (paid)", None))
        item = self.tblBalance.item(0, 2)
        item.setText(_translate("MainWindow", "0.00", None))
        item = self.tblBalance.item(1, 0)
        item.setText(_translate("MainWindow", "Sales (credit)", None))
        item = self.tblBalance.item(1, 2)
        item.setText(_translate("MainWindow", "0.00", None))
        item = self.tblBalance.item(2, 0)
        item.setText(_translate("MainWindow", "Total revenue", None))
        item = self.tblBalance.item(2, 2)
        item.setText(_translate("MainWindow", "0.00", None))
        item = self.tblBalance.item(3, 0)
        item.setText(_translate("MainWindow", "Costs", None))
        item = self.tblBalance.item(3, 1)
        item.setText(_translate("MainWindow", "0.00", None))
        item = self.tblBalance.item(4, 0)
        item.setText(_translate("MainWindow", "Taxes", None))
        item = self.tblBalance.item(4, 1)
        item.setText(_translate("MainWindow", "0.00", None))
        item = self.tblBalance.item(5, 0)
        item.setText(_translate("MainWindow", "Profit", None))
        item = self.tblBalance.item(5, 2)
        item.setText(_translate("MainWindow", "0.00", None))
        item = self.tblBalance.item(6, 0)
        item.setText(_translate("MainWindow", "Profit (margin)", None))
        item = self.tblBalance.item(6, 2)
        item.setText(_translate("MainWindow", "0.00", None))
        self.tblBalance.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_balance), _translate("MainWindow", "Balance", None))

import res_rc
