# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_sale.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.setWindowModality(QtCore.Qt.WindowModal)
        Dialog.resize(1311, 488)
        Dialog.setMinimumSize(QtCore.QSize(750, 488))
        Dialog.setMaximumSize(QtCore.QSize(16777215, 488))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/resources/product_basket-512.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setModal(True)
        self.horizontalLayout = QtGui.QHBoxLayout(Dialog)
        self.horizontalLayout.setContentsMargins(9, -1, -1, -1)
        self.horizontalLayout.setSpacing(8)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_11 = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_11)
        self.label = QtGui.QLabel(Dialog)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label)
        self.leditCode = QtGui.QLineEdit(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leditCode.sizePolicy().hasHeightForWidth())
        self.leditCode.setSizePolicy(sizePolicy)
        self.leditCode.setReadOnly(True)
        self.leditCode.setPlaceholderText(_fromUtf8(""))
        self.leditCode.setObjectName(_fromUtf8("leditCode"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.leditCode)
        self.label_10 = QtGui.QLabel(Dialog)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_10)
        self.leditName = QtGui.QLineEdit(Dialog)
        self.leditName.setReadOnly(True)
        self.leditName.setObjectName(_fromUtf8("leditName"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.leditName)
        self.label_6 = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_6)
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout_2.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_2)
        self.spnBoxQuantity = QtGui.QSpinBox(Dialog)
        self.spnBoxQuantity.setAccelerated(True)
        self.spnBoxQuantity.setKeyboardTracking(False)
        self.spnBoxQuantity.setMinimum(1)
        self.spnBoxQuantity.setMaximum(999999)
        self.spnBoxQuantity.setProperty("value", 1)
        self.spnBoxQuantity.setObjectName(_fromUtf8("spnBoxQuantity"))
        self.formLayout_2.setWidget(6, QtGui.QFormLayout.FieldRole, self.spnBoxQuantity)
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout_2.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_3)
        self.label_8 = QtGui.QLabel(Dialog)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout_2.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_8)
        self.chkBoxItbms = QtGui.QCheckBox(Dialog)
        self.chkBoxItbms.setChecked(True)
        self.chkBoxItbms.setTristate(False)
        self.chkBoxItbms.setObjectName(_fromUtf8("chkBoxItbms"))
        self.formLayout_2.setWidget(9, QtGui.QFormLayout.LabelRole, self.chkBoxItbms)
        self.label_9 = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout_2.setWidget(10, QtGui.QFormLayout.LabelRole, self.label_9)
        self.spnBoxTotalItemPrice = QtGui.QDoubleSpinBox(Dialog)
        self.spnBoxTotalItemPrice.setReadOnly(True)
        self.spnBoxTotalItemPrice.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spnBoxTotalItemPrice.setSuffix(_fromUtf8(""))
        self.spnBoxTotalItemPrice.setMaximum(999999.0)
        self.spnBoxTotalItemPrice.setObjectName(_fromUtf8("spnBoxTotalItemPrice"))
        self.formLayout_2.setWidget(10, QtGui.QFormLayout.FieldRole, self.spnBoxTotalItemPrice)
        self.label_13 = QtGui.QLabel(Dialog)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_13)
        self.cmboxClient = QtGui.QComboBox(Dialog)
        self.cmboxClient.setEditable(True)
        self.cmboxClient.setObjectName(_fromUtf8("cmboxClient"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.cmboxClient)
        self.chkBoxCredit = QtGui.QCheckBox(Dialog)
        self.chkBoxCredit.setObjectName(_fromUtf8("chkBoxCredit"))
        self.formLayout_2.setWidget(9, QtGui.QFormLayout.FieldRole, self.chkBoxCredit)
        self.spnboxCost = QtGui.QDoubleSpinBox(Dialog)
        self.spnboxCost.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.spnboxCost.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spnboxCost.setDecimals(2)
        self.spnboxCost.setMaximum(99999.0)
        self.spnboxCost.setObjectName(_fromUtf8("spnboxCost"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.spnboxCost)
        self.spnboxPrice = QtGui.QDoubleSpinBox(Dialog)
        self.spnboxPrice.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spnboxPrice.setMaximum(9999999.0)
        self.spnboxPrice.setObjectName(_fromUtf8("spnboxPrice"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.FieldRole, self.spnboxPrice)
        self.spnBoxMargin = QtGui.QDoubleSpinBox(Dialog)
        self.spnBoxMargin.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spnBoxMargin.setMaximum(999999.0)
        self.spnBoxMargin.setObjectName(_fromUtf8("spnBoxMargin"))
        self.formLayout_2.setWidget(7, QtGui.QFormLayout.FieldRole, self.spnBoxMargin)
        self.spnboxDiscount = QtGui.QDoubleSpinBox(Dialog)
        self.spnboxDiscount.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spnboxDiscount.setMaximum(99999.0)
        self.spnboxDiscount.setObjectName(_fromUtf8("spnboxDiscount"))
        self.formLayout_2.setWidget(8, QtGui.QFormLayout.FieldRole, self.spnboxDiscount)
        self.label_14 = QtGui.QLabel(Dialog)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_14)
        self.leditGroup = QtGui.QLineEdit(Dialog)
        self.leditGroup.setReadOnly(True)
        self.leditGroup.setObjectName(_fromUtf8("leditGroup"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.leditGroup)
        self.verticalLayout.addLayout(self.formLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.btnInsert = QtGui.QPushButton(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnInsert.sizePolicy().hasHeightForWidth())
        self.btnInsert.setSizePolicy(sizePolicy)
        self.btnInsert.setAutoDefault(False)
        self.btnInsert.setDefault(False)
        self.btnInsert.setObjectName(_fromUtf8("btnInsert"))
        self.horizontalLayout_3.addWidget(self.btnInsert)
        self.btnUndo = QtGui.QPushButton(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnUndo.sizePolicy().hasHeightForWidth())
        self.btnUndo.setSizePolicy(sizePolicy)
        self.btnUndo.setAutoDefault(False)
        self.btnUndo.setObjectName(_fromUtf8("btnUndo"))
        self.horizontalLayout_3.addWidget(self.btnUndo)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_4 = QtGui.QLabel(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_4)
        self.spnBoxSubtotal = QtGui.QDoubleSpinBox(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spnBoxSubtotal.sizePolicy().hasHeightForWidth())
        self.spnBoxSubtotal.setSizePolicy(sizePolicy)
        self.spnBoxSubtotal.setStyleSheet(_fromUtf8(""))
        self.spnBoxSubtotal.setWrapping(False)
        self.spnBoxSubtotal.setReadOnly(True)
        self.spnBoxSubtotal.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spnBoxSubtotal.setMaximum(99999.99)
        self.spnBoxSubtotal.setObjectName(_fromUtf8("spnBoxSubtotal"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.spnBoxSubtotal)
        self.label_7 = QtGui.QLabel(Dialog)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_7)
        self.spnBoxTaxT = QtGui.QDoubleSpinBox(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spnBoxTaxT.sizePolicy().hasHeightForWidth())
        self.spnBoxTaxT.setSizePolicy(sizePolicy)
        self.spnBoxTaxT.setReadOnly(True)
        self.spnBoxTaxT.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spnBoxTaxT.setMaximum(999999.0)
        self.spnBoxTaxT.setObjectName(_fromUtf8("spnBoxTaxT"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.spnBoxTaxT)
        self.label_12 = QtGui.QLabel(Dialog)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_12)
        self.spnBoxDiscountT = QtGui.QDoubleSpinBox(Dialog)
        self.spnBoxDiscountT.setReadOnly(True)
        self.spnBoxDiscountT.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spnBoxDiscountT.setMaximum(99999.0)
        self.spnBoxDiscountT.setObjectName(_fromUtf8("spnBoxDiscountT"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.spnBoxDiscountT)
        self.verticalLayout.addLayout(self.formLayout)
        self.line = QtGui.QFrame(Dialog)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_5 = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_5.setFrameShadow(QtGui.QFrame.Plain)
        self.label_5.setScaledContents(False)
        self.label_5.setWordWrap(False)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_5)
        self.spnBoxGrandTotal = QtGui.QDoubleSpinBox(Dialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.spnBoxGrandTotal.setFont(font)
        self.spnBoxGrandTotal.setAutoFillBackground(False)
        self.spnBoxGrandTotal.setStyleSheet(_fromUtf8(""))
        self.spnBoxGrandTotal.setFrame(True)
        self.spnBoxGrandTotal.setReadOnly(True)
        self.spnBoxGrandTotal.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spnBoxGrandTotal.setMaximum(999999.0)
        self.spnBoxGrandTotal.setObjectName(_fromUtf8("spnBoxGrandTotal"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.spnBoxGrandTotal)
        self.verticalLayout.addLayout(self.formLayout_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.btnConfirm = QtGui.QPushButton(Dialog)
        self.btnConfirm.setAutoDefault(False)
        self.btnConfirm.setObjectName(_fromUtf8("btnConfirm"))
        self.horizontalLayout_2.addWidget(self.btnConfirm)
        self.btnDelete = QtGui.QPushButton(Dialog)
        self.btnDelete.setAutoDefault(False)
        self.btnDelete.setObjectName(_fromUtf8("btnDelete"))
        self.horizontalLayout_2.addWidget(self.btnDelete)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Sale", None))
        self.label_11.setText(_translate("Dialog", "Client:", None))
        self.label.setText(_translate("Dialog", "Code:", None))
        self.leditCode.setToolTip(_translate("Dialog", "Presione Enter para \n"
"buscar item por código", None))
        self.leditCode.setWhatsThis(_translate("Dialog", "Inserte el codigo del item aqui\n"
"", None))
        self.label_10.setText(_translate("Dialog", "Name:", None))
        self.label_6.setText(_translate("Dialog", "Item Price:", None))
        self.label_2.setText(_translate("Dialog", "Quantity:", None))
        self.label_3.setText(_translate("Dialog", "Margin:", None))
        self.label_8.setText(_translate("Dialog", "Discount:", None))
        self.chkBoxItbms.setText(_translate("Dialog", "Include Tax", None))
        self.label_9.setText(_translate("Dialog", "Total Item Price:", None))
        self.spnBoxTotalItemPrice.setPrefix(_translate("Dialog", "$ ", None))
        self.label_13.setText(_translate("Dialog", "Cost:", None))
        self.chkBoxCredit.setText(_translate("Dialog", "Credit", None))
        self.spnboxCost.setPrefix(_translate("Dialog", "$ ", None))
        self.spnboxPrice.setPrefix(_translate("Dialog", "$ ", None))
        self.spnBoxMargin.setPrefix(_translate("Dialog", "% ", None))
        self.spnboxDiscount.setPrefix(_translate("Dialog", "% ", None))
        self.label_14.setText(_translate("Dialog", "Group:", None))
        self.btnInsert.setText(_translate("Dialog", "Insert", None))
        self.btnUndo.setText(_translate("Dialog", "Undo", None))
        self.label_4.setText(_translate("Dialog", "Subtotal:", None))
        self.spnBoxSubtotal.setPrefix(_translate("Dialog", "$ ", None))
        self.label_7.setText(_translate("Dialog", "Sales Tax:", None))
        self.spnBoxTaxT.setToolTip(_translate("Dialog", "7.00%", None))
        self.spnBoxTaxT.setPrefix(_translate("Dialog", "$ ", None))
        self.label_12.setText(_translate("Dialog", "Discount:", None))
        self.spnBoxDiscountT.setPrefix(_translate("Dialog", "$ ", None))
        self.label_5.setText(_translate("Dialog", "Grand Total:", None))
        self.spnBoxGrandTotal.setToolTip(_translate("Dialog", "SubTotal + \n"
"ITBMS (7.00%)", None))
        self.spnBoxGrandTotal.setPrefix(_translate("Dialog", "$ ", None))
        self.btnConfirm.setText(_translate("Dialog", "Confirm", None))
        self.btnDelete.setText(_translate("Dialog", "Delete Entry", None))

import res_rc
