# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_purchase.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.setWindowModality(QtCore.Qt.NonModal)
        Dialog.resize(220, 366)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(220, 366))
        Dialog.setMaximumSize(QtCore.QSize(400, 366))
        font = QtGui.QFont()
        font.setPointSize(10)
        Dialog.setFont(font)
        Dialog.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/resources/plus-icon-0.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setSizeGripEnabled(False)
        Dialog.setModal(True)
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(Dialog)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_2)
        self.leditName = QtGui.QLineEdit(Dialog)
        self.leditName.setPlaceholderText(_fromUtf8(""))
        self.leditName.setObjectName(_fromUtf8("leditName"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.leditName)
        self.label_5 = QtGui.QLabel(Dialog)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_5)
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_3)
        self.spnBoxQuantity = QtGui.QSpinBox(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spnBoxQuantity.sizePolicy().hasHeightForWidth())
        self.spnBoxQuantity.setSizePolicy(sizePolicy)
        self.spnBoxQuantity.setMinimumSize(QtCore.QSize(0, 0))
        self.spnBoxQuantity.setWrapping(False)
        self.spnBoxQuantity.setFrame(True)
        self.spnBoxQuantity.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.spnBoxQuantity.setAccelerated(False)
        self.spnBoxQuantity.setMaximum(999999)
        self.spnBoxQuantity.setProperty("value", 1)
        self.spnBoxQuantity.setObjectName(_fromUtf8("spnBoxQuantity"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.spnBoxQuantity)
        self.label_4 = QtGui.QLabel(Dialog)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(9, QtGui.QFormLayout.LabelRole, self.label_4)
        self.label_6 = QtGui.QLabel(Dialog)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout.setWidget(10, QtGui.QFormLayout.LabelRole, self.label_6)
        self.leditVendor = QtGui.QLineEdit(Dialog)
        self.leditVendor.setPlaceholderText(_fromUtf8(""))
        self.leditVendor.setObjectName(_fromUtf8("leditVendor"))
        self.formLayout.setWidget(10, QtGui.QFormLayout.FieldRole, self.leditVendor)
        self.label_7 = QtGui.QLabel(Dialog)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout.setWidget(11, QtGui.QFormLayout.LabelRole, self.label_7)
        self.spnBoxMin = QtGui.QSpinBox(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spnBoxMin.sizePolicy().hasHeightForWidth())
        self.spnBoxMin.setSizePolicy(sizePolicy)
        self.spnBoxMin.setAccelerated(False)
        self.spnBoxMin.setMaximum(999999)
        self.spnBoxMin.setProperty("value", 1)
        self.spnBoxMin.setObjectName(_fromUtf8("spnBoxMin"))
        self.formLayout.setWidget(11, QtGui.QFormLayout.FieldRole, self.spnBoxMin)
        self.spnBoxMax = QtGui.QSpinBox(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spnBoxMax.sizePolicy().hasHeightForWidth())
        self.spnBoxMax.setSizePolicy(sizePolicy)
        self.spnBoxMax.setAccelerated(True)
        self.spnBoxMax.setMaximum(999999)
        self.spnBoxMax.setProperty("value", 100)
        self.spnBoxMax.setObjectName(_fromUtf8("spnBoxMax"))
        self.formLayout.setWidget(12, QtGui.QFormLayout.FieldRole, self.spnBoxMax)
        self.label_9 = QtGui.QLabel(Dialog)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_9)
        self.label_10 = QtGui.QLabel(Dialog)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_10)
        self.label_8 = QtGui.QLabel(Dialog)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout.setWidget(12, QtGui.QFormLayout.LabelRole, self.label_8)
        self.cmBoxCode = QtGui.QComboBox(Dialog)
        self.cmBoxCode.setEditable(True)
        self.cmBoxCode.setObjectName(_fromUtf8("cmBoxCode"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.cmBoxCode)
        self.spnboxCost = QtGui.QDoubleSpinBox(Dialog)
        self.spnboxCost.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spnboxCost.setKeyboardTracking(False)
        self.spnboxCost.setSuffix(_fromUtf8(""))
        self.spnboxCost.setDecimals(2)
        self.spnboxCost.setMaximum(9999.0)
        self.spnboxCost.setObjectName(_fromUtf8("spnboxCost"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.spnboxCost)
        self.spnboxMargin = QtGui.QDoubleSpinBox(Dialog)
        self.spnboxMargin.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spnboxMargin.setKeyboardTracking(False)
        self.spnboxMargin.setMaximum(9999.0)
        self.spnboxMargin.setObjectName(_fromUtf8("spnboxMargin"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.spnboxMargin)
        self.spnboxPrice = QtGui.QDoubleSpinBox(Dialog)
        self.spnboxPrice.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spnboxPrice.setKeyboardTracking(False)
        self.spnboxPrice.setMaximum(99999.0)
        self.spnboxPrice.setObjectName(_fromUtf8("spnboxPrice"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.spnboxPrice)
        self.cmboxCategory = QtGui.QComboBox(Dialog)
        self.cmboxCategory.setEditable(True)
        self.cmboxCategory.setObjectName(_fromUtf8("cmboxCategory"))
        self.formLayout.setWidget(9, QtGui.QFormLayout.FieldRole, self.cmboxCategory)
        self.label_11 = QtGui.QLabel(Dialog)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_11)
        self.cmboxGroup = QtGui.QComboBox(Dialog)
        self.cmboxGroup.setEditable(True)
        self.cmboxGroup.setObjectName(_fromUtf8("cmboxGroup"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.cmboxGroup)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnAdd = QtGui.QPushButton(Dialog)
        self.btnAdd.setAutoDefault(False)
        self.btnAdd.setDefault(False)
        self.btnAdd.setObjectName(_fromUtf8("btnAdd"))
        self.horizontalLayout.addWidget(self.btnAdd)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Purchase", None))
        Dialog.setWhatsThis(_translate("Dialog", "Introduzca un código y presione Enter.\n"
"Si ya existe un registro del item, los campos se llenaran", None))
        self.label.setText(_translate("Dialog", "Code:", None))
        self.label_2.setText(_translate("Dialog", "Name:", None))
        self.label_5.setText(_translate("Dialog", "Unit Cost:", None))
        self.label_3.setText(_translate("Dialog", "Quantity:", None))
        self.label_4.setText(_translate("Dialog", "Category:", None))
        self.label_6.setText(_translate("Dialog", "Vendor:", None))
        self.label_7.setText(_translate("Dialog", "Minimum Quantity:", None))
        self.label_9.setText(_translate("Dialog", "Suggested Price:", None))
        self.label_10.setText(_translate("Dialog", "Profit Margin:", None))
        self.label_8.setText(_translate("Dialog", "Maximum Quantity:", None))
        self.spnboxCost.setPrefix(_translate("Dialog", "$ ", None))
        self.spnboxMargin.setPrefix(_translate("Dialog", "% ", None))
        self.spnboxPrice.setPrefix(_translate("Dialog", "$ ", None))
        self.label_11.setText(_translate("Dialog", "Group:", None))
        self.btnAdd.setText(_translate("Dialog", "Add", None))

import res_rc
